name: "Wait"
description: "Wait a designated number of milliseconds"
inputs:
  ssh_key:
    description: "ssh key"
    default: null
  prod_apt_deps:
    description: "wether or not to install all apt dependencies used in production envoriments"
    default: false
  chrome:
    description: "wether or not to download chrome"
    default: false
  rubocop:
    description: "wether or not to download rubocop"
    default: false
  postgres:
    default: false
    description: "wether or not to install postgresql-client and dockerize"
  gem_server_credentials:
    default: null
    description: "credentials for gem server"
runs:
  using: 'node12'
  main: 'dist/index.js'
