require "rake/testtask"
$LOAD_PATH.unshift(__dir__)

task :test do |t|
    Rake::TestTask.new(t.name) do |tt|
        tt.libs << "."
        tt.test_files = Dir.glob("test/**/*.rb")
        tt.warning = false
      end
end