name: Move To Release

on: [workflow_dispatch]

jobs:
  release: 
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: build
      - uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: release
          FOLDER: ./
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}