name: Move To Release

on: [workflow_dispatch]

jobs:
  release: 
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: build
      - run: git fetch
      - run: git checkout release
      - run: git merge build