name: Release

on: [workflow_dispatch]

jobs:
  release: 
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: build
      - run: |1
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - run: git fetch
      - run: git checkout release
      - run: git merge build --allow-unrelated-histories
      - run: git push origin release
      - name: Create Release
        id: create_release
        uses: zendesk/action-create-release@v1
        with:
          tag_schema: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "Released ${{steps.create_release.outputs.current_tag}}"