on: [push]

jobs:
  test:
    runs-on: "ubuntu-20.04"
    env:
      RACK_ENV: test
      PG_HOST: localhost
      PG_USER: backends_u
      PG_PASSWORD: abc
    steps:
      - uses: actions/checkout@v2
      - uses: quickpay/postgresql-action@v2
      - uses: ./
        with:
          ssh_key: "${{secrets.SSH_KEY_GITHUB}}"
          prod_apt_deps: true
          chrome: true
          rubocop: true 
          postgres: true
          gem_server_credentials: "${{secrets.BUNDLE_GEMS__QUICKPAY__NET}}"
      - uses: ruby/setup-ruby@v1
        with: 
          ruby-version: 2.7
      - run: git clone git@github.com:QuickPay/klarna-payments-backend.git
      - run: gem install bundler && cd klarna-payments-backend && sudo bundle install
      - run: ls -a