name: Test and Build

on: [push]

jobs:
  test:
    runs-on: "ubuntu-20.04"
    env:
      RACK_ENV: test
      PG_HOST: localhost
      PG_USER: backends_u
      PG_PASSWORD: abc
    steps:
      - uses: actions/checkout@v2
      - uses: quickpay/postgresql-action@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
          cache: "npm"
      - run: npm install && npm run build
      - uses: ./dist/
        with:
          ssh_key: "${{secrets.SSH_KEY_GITHUB}}"
          prod_apt_deps: true
          chrome: true
          rubocop: true 
          postgres: true
          gem_server_credentials: "${{secrets.BUNDLE_GEMS__QUICKPAY__NET}}"
          gem_github_credentials: ${{github.actor}}:${{secrets.GITHUB_TOKEN}}
          set_env_var: true
      - uses: ruby/setup-ruby@v1
        with: 
          ruby-version: 2.7
      - run: git clone git@github.com:QuickPay/klarna-payments-backend.git
      - run: gem install bundler
      - name: Tests
        run: cd integration_test && bundle install && bundle exec rake test
      - run: cd klarna-payments-backend && bundle install
  build:
    needs: test
    runs-on: "ubuntu-20.04"
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
          cache: "npm"
      - run: npm install && npm run build
      - uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}