name: Test and Build

on: [push]

jobs:
  test:
    runs-on: "ubuntu-20.04"
    env:
      RACK_ENV: test
      PG_HOST: localhost
      PG_USER: backends_u
      PG_PASSWORD: abc
    steps:
      - uses: actions/checkout@v2
      - uses: quickpay/postgresql-action@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
          cache: "npm"
      - run: npm install && npm run build
      - uses: ./dist/
        with:
          ssh_key: "${{secrets.SSH_KEY_GITHUB}}"
          prod_apt_deps: true
          chrome: true
          rubocop: true 
          postgres: true
          gem_server_credentials: "${{secrets.BUNDLE_GEMS__QUICKPAY__NET}}"
      - uses: ruby/setup-ruby@v1
        with: 
          ruby-version: 2.7
      - run: git clone git@github.com:QuickPay/klarna-payments-backend.git
      - run: gem install bundler
      - run: cat .rubocop.yml
      - name: Tests
        run: |1
          assert_eq(){
            exp="$1"
            shift
            act="$*"
            if [[ "$act" == *"$exp"* ]]; then
              echo "+1"
            else
              echo "failed test"
              exit 1
            fi
          }

          assert_eq "test" $(psql -d postgresql://backends_u:abc@localhost/backends_test -c "select 'test';")
      - name: Test pgcrypto is installed
        run: psql -S -d postgresql://backends_u:abc@localhost/backends_test -c "select gen_random_uuid();"
      - run: cd klarna-payments-backend && bundle install
  build:
    needs: test
    runs-on: "ubuntu-20.04"
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
          cache: "npm"
      - run: npm install && npm run build
      - uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}